name: eventpass_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  dart_jsonwebtoken: ^2.14.1
  dio: ^5.7.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  heroicons: ^0.10.0
  image: ^4.3.0
  image_picker: ^0.8.7+4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  riverpod_annotation: ^2.5.3
  shared_preferences: ^2.3.3
  syncfusion_flutter_charts: ^27.1.53

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/
